name: CEA Roster Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  validate-composer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

  run-test:
    needs: validate-composer
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2, 8.3 ]
        sqlite: [3.40.0, 3.35.0]
        stability: [ prefer-stable ]

    services:
      sqlite:
        image: docker://alpine
        options: --health-cmd="sqlite3 -version || exit 1"
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: xdebug.mode=${{ matrix.php == '8.3' ? 'coverage' : 'off' }}

      - name: Install and Update composer
        run: composer install --no-scripts

      - name: Setup environment and generate key
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate --env=testing --force

      - name: Run tests and generate coverage report
        run: composer run-script coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0

      - name: Drop migrations
        run: php artisan migrate:rollback --step=0
