name: CEA Roster Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  validate-composer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

  run-test:
    needs: validate-composer
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2, 8.3 ]
        stability: [ prefer-stable ]

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: xdebug.mode="coverage"
          coverage: xdebug

      - name: Install and Update composer
        run: composer install

      - name: Setup environment
        run: cp .env.example .env && php artisan key:generate

      - name: Set up Sql database
        run: php artisan migrate

      - name: Run test and generate coverage report
        run: php artisan test --coverage-text --coverage-clover=coverage.xml

      - name: Drop migration
        run: php artisan migrate:rollback --step=0
